apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleci-mlops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: circleci-mlops
  template:
    metadata:
      labels:
        app: circleci-mlops
    spec:
      containers:
        - name: circleci-mlops
          image: us-central1-docker.pkg.dev/golden-index-465218-f7/circleci-mlops/circleci-mlops:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: circleci-mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
